### ISSUE TITLE
Migration to v13

### ISSUE THREAD

**Issue by rousseldenis** [OCA/odoo-pim#14]
# Migration to v13

* [x] attribute_set - By @rousseldenis - #15
* [ ] attribute_set_completeness - By @simahawk - #55 
* [x] attribute_set_mass_edit  - By @simahawk - #57
* [x] attribute_set_searchable  - By @simahawk - #56
* [x] pim
* [ ]  ~~pim_attribute_set~~ Will be merged into pim
* [x] product_attribute_set
* [ ] product_attribute_set_completeness - By @simahawk - #55

**Comment by drewes** [comment]
Thanks for an awesome module. I would like to help migrating to v13. 

Odoo has removed the `orm` package and the `attribute_set` module uses the `setup_modifiers` method and fails.

I'm a bit of a noob with `orm` API. Any suggestions on what would be the best way to migrate?

**Comment by rousseldenis** [comment]
> Thanks for an awesome module. I would like to help migrating to v13.
> 
> Odoo has removed the `orm` package and the `attribute_set` module uses the `setup_modifiers` method and fails.
> 
> I'm a bit of a noob with `orm` API. Any suggestions on what would be the best way to migrate?

Hi, migration is in progress, this issue is not really up to date (see PR's).

For setup_modifiers, I copied code for the moment there https://github.com/shopinvader/odoo-pim/pull/15/files#diff-71a7774ac96833a1ecb9f1e664a466aa

**Comment by drewes** [comment]
Brill. Thanks.

**Comment by bosd** [comment]
Maybe someone can remove this pinned issue and place version 18.0 or 19.0 there? @rousseldenis 👀  Do you have some powers here?

**Comment by rvalyi** [comment]
@bosd done. Thanks for the suggestion.

**Comment by bosd** [comment]
@rvalyi Thanks! Do you have some super powers here to get some merges done? 🚀 
This repo needs a bit of oca ❤️
